name: Deploy Node.js App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:/root/.nvm/versions/node/v20.15.0/bin
            cd ~/p4p-admin-backend
            git pull https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/sanjeev567/p4p-admin-backend.git master
            npm install
            pm2 restart index.js
